spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: sys as sysdba
    password: 1231234
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      # khi chưa có thông tin consumer reset off set về 0
      auto-offset-reset: earliest
server:
  port: 8081